# Generated by Django 5.0.6 on 2024-05-28 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(blank=True, max_length=2, null=True)),
                ('motorcycle', models.CharField(blank=True, max_length=50, null=True)),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
                ('godfather', models.CharField(blank=True, max_length=50, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=50, null=True)),
                ('emergencyPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('formerMC', models.CharField(blank=True, max_length=50, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
